# Generated by Django 4.1.7 on 2023-10-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_amount_alter_scholarship_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 8, 7, 14, 588634, tzinfo=datetime.timezone.utc), help_text='Last date to apply for the scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='winner_announcement_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 21, 8, 7, 14, 588634, tzinfo=datetime.timezone.utc), help_text='Date when the winner will be announced'),
        ),
    ]
